### ISSUE TITLE
Buttons - Fill Button with 3D styles to 3D Block Style

### ISSUE THREAD

**Issue by Justinabes007** [lightspeedwp/lsx-design#109]
**Describe the bug**
Currently the default Fill Button Block style has been styled with Borders including Hover effects as per the Style Guide. 

In Practise this is not always ideal if the Button is within a Card or Box Element as it causes extra Borders & Hover display issues. 

Adjusting all the current variations of the Fill Button to move to a New Block style will require planning to map and replace the current Styles. 

Each of the following Block Styles would need to be updated and duplicated: 

1. Fill
2. Outline
3. Rounded 
4. Pill 

From each Button Block style, each Colour variation X 5 + each Hover state + Contract/Base background would need to be updated and replaced with new default style and the current Styles moved to a New 3D Block Button style. 

Screenshots: 
<img width="395" alt="Screenshot 2024-04-05 at 14 42 00" src="https://github.com/lightspeedwp/lsx-design/assets/103206213/8bc01d4d-3cdf-4f8c-a939-34d5bd2a4c2d">

**Expected behavior**

1. Fill Button shouldn't contain Borders or 3D hover states only the colour states within the same Colour Pallete 
5. The current Fill Button styles moved to a 3D Block styles 
<img width="397" alt="Screenshot 2024-04-05 at 14 45 58" src="https://github.com/lightspeedwp/lsx-design/assets/103206213/17c29fd1-047c-49b8-a897-a6a8d3fcdf77">

**Comment by krugazul** [comment]
@Justinabes007 I have tested the buttons and checked the code from the relevant branch
