### ISSUE TITLE
Button - Case select not working

### ISSUE THREAD

**Issue by Justinabes007** [lightspeedwp/lsx-design#141]
**Describe the bug**
When trying to change or update the Sentance case it doesn't reflect the changes, viewing CSS in the front end it is applied, however, conflict seems to be used via site settings somewhere. 

<img width="940" alt="Screenshot 2024-07-18 at 16 01 47" src="https://github.com/user-attachments/assets/f81aee59-dbd6-45cd-9774-87357fdc4a5a">

**Comment by krugazul** [comment]
@Justinabes007  the text transform overwritting that is coming from wordpress.   You need to add in CSS to set the transform on the link inside the button to "inherit".  It will then inherit the value from the parent element.  (you might have to use !important").  

This can go into the button css

```:root :where(.wp-block-button .wp-block-button__link) {
    text-transform: inherit;
}```
