### ISSUE TITLE
Navigation - Current states not consistant

### ISSUE THREAD

**Issue by Justinabes007** [lightspeedwp/lsx-design#142]
**Describe the bug**
The navigation block sometimes includes Current classes on active pages, however some instances no active Tab is displayed. 

Example of Active/Current state on page
<img width="1080" alt="Screenshot 2024-07-18 at 16 02 39" src="https://github.com/user-attachments/assets/33773c62-61ad-4885-834a-832ff2d6dae3">

Example of No State on page. 
<img width="1039" alt="Screenshot 2024-07-18 at 16 02 51" src="https://github.com/user-attachments/assets/f6b64303-87b5-4aab-966d-93550404defc">

**Comment by krugazul** [comment]
@Justinabes007  this was a block useage issue,  if you "duplicate" the blog category link block, it is still tied in to that category.   Even if you change the link.    You have to add a new category block in from scratch.
