### ISSUE TITLE
Search Results - The "No Results" pattern is missing

### ISSUE THREAD

**Issue by Justinabes007** [lightspeedwp/lsx-design#143]
**Describe the bug**
The "No Results" pattern is missing, this seems to be a parent-theme issue

![screenshot (1)](https://github.com/user-attachments/assets/1c029ecc-f91d-4df0-9595-aa845be50fb2)

**Comment by krugazul** [comment]
@Justinabes007 ,   the template is referencing a block thats not available, we need to replace it with the no results block.
[https://github.com/lightspeedwp/lsx-design/blob/main/templates/search.html#L43](https://github.com/lightspeedwp/lsx-design/blob/main/templates/search.html#L43)

**Comment by Justinabes007** [comment]
No Results Block added back to template - https://github.com/lightspeedwp/lsx-design/commit/561e8b7336bc46e50d3462a2e38a1dec77364efd

Tested locally & Demo, small bug fix.
