### ISSUE TITLE
Shadow block styles on Group block do not display in the Site Editor

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#145]
**Describe the bug**
When using the site editor (in the backend), applying the shadow block style to the group block works in the frontend, but does not display in the backend. The preview also does not Display the correct sample. 

**To Reproduce**
1. Go to the Site Editor, select a template with a query loop
2. Click into the Query Loop, then select the contents of the "Post Template" and apply the group block to them
3. Next go to the "Styles" hover over one of the shadow block styles and see the incorrect preview.
4. Click any shadow block style 

**Expected behavior**
The shadow style should display in the backend as well as the frontend, but it does not.

**Screenshots**
![Screenshot 2024-07-24 at 09 17 28 (2)](https://github.com/user-attachments/assets/424a9b4d-8749-4122-9386-66e62b0a315f)

**Comment by Justinabes007** [comment]
Bug in code identified. The code referenced the wrong block and was set to **Column** and not **Group**. 

Adjusting the code resolves the issue, and block styles are displayed in the editor. It works on child themes as well. 
Commit of code - https://github.com/lightspeedwp/lsx-design/commit/00e4b885ecd27c97e01d82145fc24968b3764fb2

**Screenshot of code:** 
![Screenshot 2024-07-26 at 13 02 05](https://github.com/user-attachments/assets/3887842e-8242-4b1f-b00a-09c2bca3956d)
