### ISSUE TITLE
Increase the padding between the menu items and the submenus

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/lsx-design#16]
When you hover over a menu item, the submenu sits flush with the menu item above.

**Solution**
We need to increase the bottom and top padding on the LI element, and reduce the padding of the header.   To allow the mouse to keep the submenu open when navigating to it.

**Additional context**
![Screenshot 2023-06-26 at 16 41 47](https://github.com/lightspeedwp/lsx-design/assets/1805603/b8dea44c-5632-47d0-b30f-daa3dc56ab8f)

**Comment by Justinabes007** [comment]
Was already resolved in previous commits.
