### ISSUE TITLE
Search results are limited to one page

### ISSUE THREAD

**Issue by carolinan** [lightspeedwp/lsx-design#18]
**Describe the bug**
The search template limits the results to one page:
[`<!-- wp:query {"queryId":0,"query":{"pages":1,"`](https://github.com/lightspeedwp/lsx-design/blob/a34e1af24727b0e3f0832962c0a2307dcc470533/templates/search.html#L10C2-L10C62)

The number of results that show match the setting in the WordPress Admin > Reading > Blog pages show at most.

- If this is intentional, the query pagination block can be removed from the template because it will never be used.
- Or, To display all results, paginated, set `"pages": 1` to `"pages": 0 `in the comment for the query block.

**To Reproduce**
1. On the font of the website, perform a search and view the search results page.

**Expected behavior**
To display all results

**Comment by krugazul** [comment]
Correct in commit [c35168c](https://github.com/lightspeedwp/lsx-design/pull/33/commits/c35168cde838b05c1fa73656641fc251ee6e81c1)
