### ISSUE TITLE
The search results template is missing the "no results" block

### ISSUE THREAD

**Issue by carolinan** [lightspeedwp/lsx-design#19]
**Describe the bug**
When there are no search results, the page displays the search form in the top part of the page but not a
message explaining that there were no results. The rest of the page is empty.
This is, of course, optional but common practice.

To add blocks that are only shown when there are no results, add the "no results" block inside the query loop, but outside the post template block. The block itself does not display anything; it only displays the blocks you place inside it.

**To Reproduce**
1. Perform a search that you know will have no results on your test site.
2. View the empty page.

**Expected behavior**
A message explaining there were no results, and maybe some guidance on what to do next, for example,
list the most recent posts or most popular products.

**Comment by krugazul** [comment]
@carolinan we have added in the no results template, it is just a text prompt for now.  Ive created an Issue to work on a more enhanced version of that. (we will need to discuss it internally and decide what we want.)

[https://github.com/lightspeedwp/lsx-design/issues/29](https://github.com/lightspeedwp/lsx-design/issues/29)
