### ISSUE TITLE
Archives: The category is covering the post title on small screens

### ISSUE THREAD

**Issue by carolinan** [lightspeedwp/lsx-design#20]
**Describe the bug**
When the browser window width is reduced, the category name, which is displayed to the right of the post title, comes closer and closer to the title. Eventually, the category covers part of the title.

**To Reproduce**
View an archive page and reduce the browser window width.

**Expected behavior**
All texts should be readable.

**Screenshots**

https://github.com/lightspeedwp/lsx-design/assets/7422055/f0ae6416-cb62-4715-aa6d-d5411892672a

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Chrome

**Comment by Justinabes007** [comment]
Applied styling to ensure text is visible all the time.
