### ISSUE TITLE
Nit: hyphens (-) are converted to unicode characters

### ISSUE THREAD

**Issue by carolinan** [lightspeedwp/lsx-design#21]
**Describe the bug**
In some of the templates and patterns,  the hyphens in the block comment are replaced with Unicode.
so instead of `wp--custom--spacing` etc, it says `var(\u002d\u002dwp\u002d\u002dcustom\u002d\u002dspacing\u002d\u002dlarge`

**To Reproduce**
View the source of the header template parts and header patterns.

**Expected behavior**
The **recommended** format for the CSS variables in the block comments is `"var:preset|spacing|70"`
Using `var(--wp--preset--spacing--70` also works.

**Notes**

- [ ] Woo Header Dark
- [ ] Woo Header Light
- [ ] Review the Patterns

**Comment by Justinabes007** [comment]
Unicode characters removed - https://github.com/lightspeedwp/lsx-design/commit/c980ab34846c466459216812853b6834bd0c45c7
