### ISSUE TITLE
Nit: Remove unused files and add credit for borrowed code

### ISSUE THREAD

**Issue by carolinan** [lightspeedwp/lsx-design#22]
**Describe the bug**
There seem to be several block patterns that are included as files but not used.

Please also remember that GPL allows re-using code from other GPL products, but adding copyright information and license information for that product is required.
So if you borrow patterns and code from the "Frost" theme and Storefront, you can, but you need to add credits, for example in the readme file.

**Comment by Justinabes007** [comment]
Reference & unused Patterns removed.
