### ISSUE TITLE
Spacing improvements to Blog Archive & Single templates 

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#32]
**Describe the issue**
Spacing improvements to Blog Archive & Single templates. 

**To Reproduce**
Steps to reproduce the spacing issues:
- Review the comments on bugherd - https://www.bugherd.com/projects/355612/kanban
- Open the Blog archive demo link - https://demo.lsx.design/blog/
- Open the Blog single demo link - https://demo.lsx.design/gutenberg-common-blocks-2/

**Designs**
- Compare the above demo links to the designs and align the theme's spacing with the design. 
- Blog Archive design on Figma - https://www.figma.com/file/U3MB5DRLxHpQDoDs2Pi2jG/LSX-WordPress?type=design&node-id=713%3A22682&mode=design&t=rzqfXc6QS4JFoeUe-1
- Single Blog design on Figma - https://www.figma.com/file/U3MB5DRLxHpQDoDs2Pi2jG/LSX-WordPress?type=design&node-id=713-26199&t=WBXP7cbA8gGvzJhW-0

**Comment by krugazul** [comment]
@Justinabes007 I have moved this to milestone 1.1.1
