### ISSUE TITLE
Gravity Forms - Form Block Compatability

### ISSUE THREAD

**Issue by krugazul** [lightspeedwp/lsx-design#56]
**Description**
There is no CSS for the Gravity Forms "form block" in the theme. Currently the button does not inherit the 

**Prep**
- [x] Decide which colour variables the form will use from the theme.json
- [ ] Add in Block CSS for the "Form Block".
- [x] Setup a full form with all the types of fields neccesary.

**Styling**
- [x] Buttons (next page, submit, upload image etc)
- [x] Field Labels
- [x] Field inputs
- [x] Field inputs when active
- [x] Field inputs with validation errors
- [x] Confirmation message once submitted
- [x] Mobile Layout

**Current Form**
<img width="523" alt="Screenshot 2023-11-13 at 10 44 45" src="https://github.com/lightspeedwp/lsx-design/assets/1805603/caf45ba2-cce3-4291-a40b-34c2327e90c8">

**Additional context**
The old LSX for reference - [https://lsx-demo-staging.lightspeedwp.dev/contact/](https://lsx-demo-staging.lightspeedwp.dev/contact/)

**Comment by Justinabes007** [comment]
Commit of Styling fixes - https://github.com/lightspeedwp/lsx-design/commit/cfc65354996bac25f9c8cc770d6152b752f6a787 

Resolved the Default Gravity Forms Styling issues. Block specific CSS still required.
