### ISSUE TITLE
Switch WooCommerce Products Block and Product Archive Block Templates

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#60]
**WooCommerce Product Archives are using classic templates**

- [x] Product Catalog (Shop page) 
- [x] Products by category - https://www.bugherd.com/projects/355612/tasks/18
- [x] Products by tag - https://www.bugherd.com/projects/355612/tasks/26
- [x] Products by attribute

**Switch WooCommerce Products Block and Product Archive Block Templates**

- [x] Start by opening the site editor, open each archive template and transform the classic template to the new block template. 
- [x] Style the pages to look like the design

### Screenshots

- **Product catalog archive aka Shop page** - https://demo.lsx.design/shop

![Image](https://github.com/lightspeedwp/lsx-design/assets/1805352/777c363c-1c11-405e-aa6a-afe0b02444b2)

- **Product Category Archive** - https://demo.lsx.design/product-category/clothing/

![Image](https://github.com/lightspeedwp/lsx-design/assets/1805352/8bd06d0f-d6f0-4e76-9385-b87fe5fa65cb)

- **Product Tag Archive** - https://demo.lsx.design/product-tag/example/

![Image](https://github.com/lightspeedwp/lsx-design/assets/1805352/1a34f282-da79-4ff2-9514-12f6a7fbcf1c)

- **Product Attribute Archive** - https://demo.lsx.design/colour/blue/

![Image](https://github.com/lightspeedwp/lsx-design/assets/1805352/04dec4a4-91bf-478a-9294-984f0664aca9)

**Comment by Justinabes007** [comment]
#70 Includes Woocommerce Templates for LSX Design. 

- Checkout - added
- Single - added
- Catalog/Product Archive - update
- Category Archive - update
- Tag Archive - added
- Tag Archive - added
- Product Attribute Archive

**Comment by Justinabes007** [comment]
#70 has been merged with Version 1.2.0
