### ISSUE TITLE
Product Search Results Block Template

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#67]
**Product Search Results using Classic Search Template**
- No dedicated block template, the theme is still using the classic Woo template.
- Bugherd task - https://www.bugherd.com/projects/355612/tasks/60

**Add a block template to the Templates folder**
- [x] Add product search results block template
- [x] Template should use of the "Product Filters" blocks and the new "Product Collection Block".

### Screenshot
- Demo site - https://demo.lsx.design/?s=product&post_type=product

![lsx-design-product-search-results-with-filters](https://github.com/lightspeedwp/lsx-design/assets/1805352/5e016473-d1ea-4a39-8994-dba238a5b511)

**Comment by Justinabes007** [comment]
#70 Includes addition of the **Woocommerce Product Search Template**: product-search-results.html - https://github.com/lightspeedwp/lsx-design/blob/e19df889b0dae5ac20befbed6b4d5019270e2a48/templates/product-search-results.html

1. Template added to theme
2. Template uses the "Product Filters" blocks and the new "Product Collection Block". 

### Test completed: 
- [x] Tested Locally 
- [x] Tested on Fresh install 
- [x] Designs display as intended
