### ISSUE TITLE
Additional Block Styles for the Paragraph block

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeedwp/lsx-design#75]
**Currently it is manual process of adding properties**
There is no standard way to easily apply a subheading style. When we manually set font sizes they no longer respond to the theme defaults. 

**Add 3 new block styles**
- Subheading H1 - Font size 48; Appearance Medium
- Subheading H2 - Font size 30; Appearance Medium
- Subheading H3 - Font size 24; Appearance Medium

**Comment by Justinabes007** [comment]
#76 includes solution for Block Styles for the Paragraph block.
